# This rule is not used by the project k8s-foo-controller itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over foogroup.foo.controller.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: k8s-foo-controller
    app.kubernetes.io/managed-by: kustomize
  name: foolabel-admin-role
rules:
- apiGroups:
  - foogroup.foo.controller
  resources:
  - foolabels
  verbs:
  - '*'
- apiGroups:
  - foogroup.foo.controller
  resources:
  - foolabels/status
  verbs:
  - get
