---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - foogroup.foo.controller
  resources:
  - foolabels
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - foogroup.foo.controller
  resources:
  - foolabels/finalizers
  verbs:
  - update
- apiGroups:
  - foogroup.foo.controller
  resources:
  - foolabels/status
  verbs:
  - get
  - patch
  - update
